### PR TITLE
kv.rb new features

### PR DESCRIPTION
**Pull request by urielha**
Hi,
This is the pull request elasticsearch/logstash#1486 from [elasticsearch/logstash](https://github.com/elasticsearch/logstash) you asked me to reopen here
the features:
* support spaces between key and value_split
* support brackets 
* recursive option

### CODE REVIEW

**Comment by suyograo** [comment]
@urielha can you sign the CLA https://github.com/elasticsearch/logstash/blob/master/CONTRIBUTING.md#contribution-steps

**Comment by suyograo** [comment]
Also needs a rebase. Sorry for the delays!

**Comment by urielha** [comment]
Hi @suyograo,
I have signed the CLA and rebase my changes onto master.

Let me know if there is another issue,
Thanks :)

**Comment by jordansissel** [comment]
The commit message says "conflicts ..." - did a merge go badly or something? Does it need to be in the commit message like this?

**Comment by urielha** [comment]
Ah.. The tool added this automatically..
The merge went good, I can "amend" the commit

**Pull request closed without merging**
